language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
env: FXCONNECT_HOME=~/ForexConnectAPI-1.2.0-Linux-i686
before_install:
  - curl --insecure https://files.fxcorporate.com/api/fxc/ForexConnectAPI-1.2.0-Linux-i686.tar.gz | tar zxf -
  - echo $FXCONNECT_HOME
  - ls -l $FXCONNECT_HOME
install:
  - cpanm -v --installdeps --notest .
before_scrpt:
  - echo $FXCONNECT_HOME
