language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
env: CPLUS_INCLUDE_PATH=~/ForexConnectAPI-1.2.2-Linux-i686/include C_INCLUDE_PATH=~/ForexConnectAPI-1.2.2-Linux-i686/include LD_LIBRARY_PATH=~/ForexConnectAPI-1.2.2-Linux-i686/lib FXCM_USER=GBD118836001 FXCM_PASSWORD=5358
before_install:
  - curl --insecure https://files.fxcorporate.com/api/fxc-1.2.2/ForexConnectAPI-1.2.2-Linux-i686.tar.gz | tar zxf - -C ~
install:
  - cpanm -v --installdeps --notest --mirror http://cpan.mirrors.travis-ci.org .
