Name:           perl-Finance-FXCM-Simple
Version:        0.010
Release:        1%{?dist}
Summary:        Synchronous wrapper to the FXCM ForexConnect API which is simple to use
License:        MIT
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Finance-FXCM-Simple/
Source0:        http://www.cpan.org/modules/by-module/Finance/Finance-FXCM-Simple-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Scalar::Util)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(YAML::XS)
BuildRequires:  libforexconnect-devel
Requires:       perl(YAML::XS)
Requires:       libforexconnect
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module allows you to open/close/query positions in both real or demo
FXCM trading accounts, as well as download historical price data for
instruments supported by FXCM.

%prep
%setup -q -n Finance-FXCM-Simple-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes LICENSE perlobject.map README README.md
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Finance*
%{_mandir}/man3/*

%changelog
* Sun Mar 24 2013 João Costa <joaocosta@zonalivre.org> 0.010-1
- Updated to latest version
* Wed Nov 14 2012 João Costa <joaocosta@zonalivre.org> 0.008-1
- Specfile autogenerated by cpanspec 1.78.
